/*
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/person.proto

package com.gangdan.netty.protocol;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gangdan.netty.protocol.Person)
    com.google.protobuf.MessageOrBuilder {

  */
/**
   * <code>optional int32 id = 1;</code>
   *//*

  int getId();

  */
/**
   * <code>optional string name = 2;</code>
   *//*

  String getName();

  */
/**
   * <code>optional string name = 2;</code>
   *//*

  com.google.protobuf.ByteString
  getNameBytes();

  */
/**
   * <pre>
   *    reserved "foo", "bar";
   *    repeated Result results = 1;
   * </pre>
   * <p>
   * <code>optional string email = 3;</code>
   *//*

  String getEmail();

  */
/**
   * <pre>
   *    reserved "foo", "bar";
   *    repeated Result results = 1;
   * </pre>
   * <p>
   * <code>optional string email = 3;</code>
   *//*

  com.google.protobuf.ByteString
  getEmailBytes();
}
*/
